### ISSUE TITLE
TypeError: _compute_mask_indices() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by ja5p3r** [b04901014/FT-w2v2-ser#1]
Hi while running run_downstream_custom_multiple_fold.py, I ran into 
TypeError: _compute_mask_indices() got an unexpected keyword argument 'device'
In package transformers modeling_wav2vec2.py also shows that _compute_mask_indices() does not take arg device
Am I missing something here?

Any help is appreciated!

**Comment by b04901014** [comment]
I think you installed the latest version 4.12.0 released recently where they changed the function arguments of `_compute_mask_indices()`.
We haven't update that correspondingly and the code is compatible for version 4.10.0. You can view the `docker/Dockerfile` for the specific version of packages that is compatible when the project is finished.
Or you can just try to just delete the device argument.

`_compute_mask_indices()` of before 4.11.3:
https://huggingface.co/transformers/v4.11.3/_modules/transformers/models/wav2vec2/modeling_wav2vec2.html#Wav2Vec2Model

**Comment by ja5p3r** [comment]
Understood  Thanks!
